name: Build APK

on:
  push:
    branches:
      - main
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar JDK para Android
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Simular Caché de dependencias de Gradle (opcional)
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    # 4. Simular Construcción de la APK/AAB
    - name: Simular Build APK
      run: echo "Simulando construcción de APK/AAB" && mkdir -p app/build/outputs/apk/release && echo "Fake APK content" > app/build/outputs/apk/release/app-release.apk

    # 5. Subir el APK simulado como artefacto
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
