name: Build APK

on:
  push:
    branches:
      - main  # Cambia esto a la rama que desees

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar JDK para Android
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Configurar caché de dependencias de Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    # 4. Construir la APK/AAB
    - name: Build APK
      run: ./gradlew assembleRelease # Cambia a `bundleRelease` para AAB

    # 5. Guardar el APK/AAB como artefacto
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk # Cambia la ruta si usas AAB
